// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type ProductionStep int32

const (
	ProductionStepToDo     ProductionStep = 0
	ProductionStepDoing    ProductionStep = 1
	ProductionStepComplete ProductionStep = 2
	ProductionStepRelease  ProductionStep = 3
)

var EnumNamesProductionStep = map[ProductionStep]string{
	ProductionStepToDo:     "ToDo",
	ProductionStepDoing:    "Doing",
	ProductionStepComplete: "Complete",
	ProductionStepRelease:  "Release",
}

var EnumValuesProductionStep = map[string]ProductionStep{
	"ToDo":     ProductionStepToDo,
	"Doing":    ProductionStepDoing,
	"Complete": ProductionStepComplete,
	"Release":  ProductionStepRelease,
}

func (v ProductionStep) String() string {
	if s, ok := EnumNamesProductionStep[v]; ok {
		return s
	}
	return "ProductionStep(" + strconv.FormatInt(int64(v), 10) + ")"
}
