// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type ScenarioCharacterShapes int32

const (
	ScenarioCharacterShapesNone            ScenarioCharacterShapes = 0
	ScenarioCharacterShapesSignal          ScenarioCharacterShapes = 1
	ScenarioCharacterShapesBlackSilhouette ScenarioCharacterShapes = 2
	ScenarioCharacterShapesCloseup         ScenarioCharacterShapes = 4
	ScenarioCharacterShapesHighlight       ScenarioCharacterShapes = 8
)

var EnumNamesScenarioCharacterShapes = map[ScenarioCharacterShapes]string{
	ScenarioCharacterShapesNone:            "None",
	ScenarioCharacterShapesSignal:          "Signal",
	ScenarioCharacterShapesBlackSilhouette: "BlackSilhouette",
	ScenarioCharacterShapesCloseup:         "Closeup",
	ScenarioCharacterShapesHighlight:       "Highlight",
}

var EnumValuesScenarioCharacterShapes = map[string]ScenarioCharacterShapes{
	"None":            ScenarioCharacterShapesNone,
	"Signal":          ScenarioCharacterShapesSignal,
	"BlackSilhouette": ScenarioCharacterShapesBlackSilhouette,
	"Closeup":         ScenarioCharacterShapesCloseup,
	"Highlight":       ScenarioCharacterShapesHighlight,
}

func (v ScenarioCharacterShapes) String() string {
	if s, ok := EnumNamesScenarioCharacterShapes[v]; ok {
		return s
	}
	return "ScenarioCharacterShapes(" + strconv.FormatInt(int64(v), 10) + ")"
}
