// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ScenarioScriptExcel struct {
	_tab flatbuffers.Table
}

func GetRootAsScenarioScriptExcel(buf []byte, offset flatbuffers.UOffsetT) *ScenarioScriptExcel {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ScenarioScriptExcel{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsScenarioScriptExcel(buf []byte, offset flatbuffers.UOffsetT) *ScenarioScriptExcel {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ScenarioScriptExcel{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ScenarioScriptExcel) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ScenarioScriptExcel) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ScenarioScriptExcel) GroupId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ScenarioScriptExcel) MutateGroupId(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *ScenarioScriptExcel) SelectionGroup() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ScenarioScriptExcel) MutateSelectionGroup(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *ScenarioScriptExcel) Bgmid() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ScenarioScriptExcel) MutateBgmid(n int64) bool {
	return rcv._tab.MutateInt64Slot(8, n)
}

func (rcv *ScenarioScriptExcel) Sound() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ScenarioScriptExcel) Transition() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ScenarioScriptExcel) MutateTransition(n uint32) bool {
	return rcv._tab.MutateUint32Slot(12, n)
}

func (rcv *ScenarioScriptExcel) Bgname() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ScenarioScriptExcel) MutateBgname(n uint32) bool {
	return rcv._tab.MutateUint32Slot(14, n)
}

func (rcv *ScenarioScriptExcel) Bgeffect() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ScenarioScriptExcel) MutateBgeffect(n uint32) bool {
	return rcv._tab.MutateUint32Slot(16, n)
}

func (rcv *ScenarioScriptExcel) PopupFileName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ScenarioScriptExcel) ScriptKr() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ScenarioScriptExcel) TextJp() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ScenarioScriptExcel) VoiceId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ScenarioScriptExcel) MutateVoiceId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(24, n)
}

func ScenarioScriptExcelStart(builder *flatbuffers.Builder) {
	builder.StartObject(11)
}
func ScenarioScriptExcelAddGroupId(builder *flatbuffers.Builder, groupId int64) {
	builder.PrependInt64Slot(0, groupId, 0)
}
func ScenarioScriptExcelAddSelectionGroup(builder *flatbuffers.Builder, selectionGroup int64) {
	builder.PrependInt64Slot(1, selectionGroup, 0)
}
func ScenarioScriptExcelAddBgmid(builder *flatbuffers.Builder, bgmid int64) {
	builder.PrependInt64Slot(2, bgmid, 0)
}
func ScenarioScriptExcelAddSound(builder *flatbuffers.Builder, sound flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(sound), 0)
}
func ScenarioScriptExcelAddTransition(builder *flatbuffers.Builder, transition uint32) {
	builder.PrependUint32Slot(4, transition, 0)
}
func ScenarioScriptExcelAddBgname(builder *flatbuffers.Builder, bgname uint32) {
	builder.PrependUint32Slot(5, bgname, 0)
}
func ScenarioScriptExcelAddBgeffect(builder *flatbuffers.Builder, bgeffect uint32) {
	builder.PrependUint32Slot(6, bgeffect, 0)
}
func ScenarioScriptExcelAddPopupFileName(builder *flatbuffers.Builder, popupFileName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(popupFileName), 0)
}
func ScenarioScriptExcelAddScriptKr(builder *flatbuffers.Builder, scriptKr flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(scriptKr), 0)
}
func ScenarioScriptExcelAddTextJp(builder *flatbuffers.Builder, textJp flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(9, flatbuffers.UOffsetT(textJp), 0)
}
func ScenarioScriptExcelAddVoiceId(builder *flatbuffers.Builder, voiceId uint32) {
	builder.PrependUint32Slot(10, voiceId, 0)
}
func ScenarioScriptExcelEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
